---
platform: linux

inputs:
- name: env

params:
  # ENV_FILE: env.yml
  # MANIF_FILE: env.yml
  # OPS_FILE:
  # DEPLOYMENT_NAME:
  DRY_RUN: false
run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -e
    eval "$(om --env env/"${ENV_FILE}" bosh-env)"
    if [ "${DRY_RUN}" == true ] ;
    then
     bosh -n -d "${DEPLOYMENT_NAME}" deploy \
      -o env/"${OPS_FILE}" \
      env/"${MANIF_FILE}" \
      --dry-run 
      
    else
      bosh -n -d "${DEPLOYMENT_NAME}" deploy \
      -o env/"${OPS_FILE}" \
      env/"${MANIF_FILE}" 
    fi
    bosh -d -d "${DEPLOYMENT_NAME}" is --column=IPs