resources:

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_buckets_pivnet_products))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp:  platform-automation/platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((s3_access_key_id))
    bucket: ((s3_buckets_pivnet_products))
    endpoint: ((s3_endpoint))
    secret_access_key: ((s3_secret_access_key))
    regexp: platform-automation/platform-automation-image-(.*).tgz




- name: config
  type: git
  source:
    uri: ((pipeline-repo))
    private_key: ((git.private_key))
    branch: master

credhub-interpolate: &interpolate-creds
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: ((credhub-client))
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_SERVER: ((credhub-server))
    CREDHUB_CA_CERT: ((credhub-ca.ca))
    PREFIX: /concourse/((foundation))
    INTERPOLATION_PATHS: ((foundation))
  input_mapping:
    files: config
  output_mapping:
    interpolated-files: interpolated-creds

jobs:
- name: deploy-dry-run
  serial: true
  plan:
    - get: platform-automation-image
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: config
    - task: credhub-interpolate
      <<: *interpolate-creds
    - task: deploy-dry-run
      image: platform-automation-image
      file: config/tasks/deploy-concourse.yml
      params:
        ENV_FILE: ((foundation))/env/env.yml
        MANIF_FILE: ((foundation))/manifest/jumpbox/jumpbox.yml
        OPS_FILE: ((foundation))/manifest/jumpbox/add-user-op.yml
        DEPLOYMENT_NAME: ((jumpbox_deployment_name))
        DRY_RUN: true
      input_mapping:
        env: interpolated-creds

- name: deploy
  serial: true
  plan:
    - get: platform-automation-image
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: config
      passed:
        - deploy-dry-run
      trigger: false
    - task: credhub-interpolate
      <<: *interpolate-creds
    - task: deploy
      image: platform-automation-image
      file: config/tasks/deploy-concourse.yml
      params:
        ENV_FILE: ((foundation))/env/env.yml
        MANIF_FILE: ((foundation))/manifest/jumpbox/jumpbox.yml
        OPS_FILE: ((foundation))/manifest/jumpbox/add-user-op.yml
        DEPLOYMENT_NAME: ((jumpbox_deployment_name))
      input_mapping:
        env: interpolated-creds
